### ISSUE TITLE
Bungeecord Issues (Not "Running"/Initial Config Not Applying)

### ISSUE THREAD

**Issue by philip-ulrich** [SpaceCP/Bugs#192]
I appreciate the (rough) bungeecord support, but there are currently a few issues. One is that when you create a new instance, the options you choose (port,ram,players) aren't all (if any) being recognized. Additionally, it persistently shows as "starting" and never running. Attached screenshots might be helpful to you. 

http://d.l33t.tech/jZSn/3YwdeN90
http://d.l33t.tech/174rk/4RPPjKw0

**Comment by tlaundal** [comment]
Thanks for the report!

We are currently working on redesigning our internal APIs, and this issue will probably be fixed by that.
Thank you for your patience.

**Comment by JamyDev** [comment]
Hey there, you seem to have reported a few bugs. I'll go through each of them:
- Not "Running" is indicative of not using the correct mod. I'm assuming it still shows as vanilla Minecraft for you in the panel? What you could do right now to resolve this is reinstall "bungeecord" on the server through the panel. This should update the mod value.
  - If this doesn't work, or you set it up as BungeeCord, please update your daemon.
- Port and Ram should be assigned correctly (if you have the latest version of the daemon), players not yet but this is coming.
- Other reported issue: "server.properties" being created: Only if you're using an old version of the daemon.

So it sounds to me like you're using an outdated daemon.

Hope this helped!

**Comment by JamyDev** [comment]
I was able to confirm the server.properties and post assignment bugs. I'll be fixing them this weekend for sure.

**Comment by philip-ulrich** [comment]
Yeah Jamy. Don't go blaming me or my daemon for real issues. :P I'll try to force an update and see if that takes care of the running/starting issue.

I know they are multiple "issues", but I figured they were related so I just pushed em as one. :)

**Comment by philip-ulrich** [comment]
Bungeecord is now showing as running, as expected. The old daemon was the cause. I'm glad to hear that you will be fixing the other issues this weekend. Thanks as always, man!
